# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

linux build:
  image: python:3.9-bullseye
  stage: build
  script:
    - apt-get update
    - apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev python3-setuptools python3-dev python3-numpy fontconfig
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -r requirements.txt
    - python -m pip install .
    - pyinstaller -y -w --contents-directory . --add-data "lang:lang" --add-data "map_levels:map_levels" --add-data "fonts:fonts" --add-data "sprites:sprites" --add-data "palettes:palettes" --add-data "jaba_is_logo.png:." --add-data "saves:saves" --add-data "levels:levels" main.py
    - tar cfJ jaba_is_you-linux.tar.xz dist/main/
    - deactivate
  cache:
    key: linux-build-cache
    paths:
      - .cache/pip
      - venv/
  artifacts:
    paths:
      - jaba_is_you-linux.tar.xz
    expire_in: 3 weeks

windows build:
  image: python:3.11.6-windowsservercore-1809
  stage: build
  tags:
    - windows
  script:
    - Invoke-WebRequest -UseBasicParsing -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile .\vs_BuildTools.exe
    - Invoke-WebRequest -UseBasicParsing -Uri https://www.7-zip.org/a/7zr.exe -OutFile .\7z.exe
    - Start-Process -Wait .\vs_BuildTools.exe -ArgumentList "--quiet", "--nocache", "--wait", "--norestart", "--add", "Microsoft.VisualStudio.Workload.VCTools;includeRecommended"
    - python -m venv venv
    - venv\Scripts\Activate.ps1
    - python -m pip install -r requirements.txt
    # - python -m pip install . # This shit is not working in Windows
    - python setup.py install
    - pyinstaller -y -w --contents-directory . --add-data "lang;lang" --add-data "map_levels;map_levels" --add-data "fonts;fonts" --add-data "sprites;sprites" --add-data "palettes;palettes" --add-binary "jaba_is_logo.png;." --add-data "saves;saves" --add-data "levels;levels" main.py
    - .\7z.exe a jaba_is_you-windows.7z dist/
  cache:
    key: windows-build
    paths:
      - .cache/pip
      - venv/
  artifacts:
    paths:
      - jaba_is_you-windows.7z
    expire_in: 3 weeks

deploy to heroku:
  image:
    name: alpine/git
    entrypoint: [""]
  stage: deploy
  script:
    - rm -rf jaba-is-you || true
    - git clone https://heroku:$HEROKU_API_KEY@git.heroku.com/jaba-is-you.git
    - mv jaba_is_you-windows.tar.xz ./jaba-is-you/jaba_is_you-windows.tar.xz
    - mv jaba_is_you-linux.tar.xz ./jaba-is-you/jaba_is_you-linux.tar.xz
    - cd jaba-is-you/
    - git config --global user.name "CI/CD"
    - git config --global user.email "quswadress@gitlab.informatics.ru"
    - git add .
    - git commit --allow-empty -m "add executables for Windows 10 and Ubuntu"
    - git push --progress origin HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
